CREATE TABLE users (
	userId BIGINT PRIMARY KEY AUTO_INCREMENT,
	email VARCHAR(75) NOT NULL UNIQUE,
	password VARCHAR(128) NOT NULL,
	enabled BOOLEAN NOT NULL
);

CREATE TABLE roles (
	roleId BIGINT PRIMARY KEY AUTO_INCREMENT,
	roleName VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE user_role (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	userId BIGINT NOT NULL,
	roleId BIGINT NOT NULL,
	UNIQUE (userId, roleId),
	FOREIGN KEY (userId) REFERENCES users(userId),
	FOREIGN KEY (roleId) REFERENCES roles(roleId)
);

CREATE TABLE books (
	id LONG NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(128) NOT NULL,
	author VARCHAR(128) NOT NULL
);

CREATE TABLE reviews (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    bookId BIGINT NOT NULL,
    text VARCHAR(1024) NOT NULL,
    FOREIGN KEY (bookId) REFERENCES books(id)
);
